import fs from 'node:fs';
const path = 'index.js';
const raw = fs.readFileSync(path,'utf8');
const eol = raw.includes('\r\n') ? '\r\n' : '\n';
let source = raw.replace(/\r\n/g,'\n');
const pattern = /function isExplicitManualScheduleRow\(row\) \{[\s\S]*?\n\}/;
const match = source.match(pattern);
if (!match) throw new Error('manual Schedule identity helper not found');
const replacement = `function isExplicitManualScheduleRow(row) {\n\tif (!row || typeof row !== 'object' || Array.isArray(row)) return false;\n\t// Current one-off Schedule creation persists this explicit marker. A stale\n\t// generatedByPlanner=false flag is not sufficient evidence of manual origin:\n\t// migrated generated rows can carry it and must remain durably deletable.\n\treturn row?.manualScheduleEntry === true;\n}`;
source = source.replace(pattern,replacement);
const out = eol === '\r\n' ? source.replace(/\n/g,'\r\n') : source;
fs.writeFileSync(path,out,'utf8');
console.log('BACKEND_MANUAL_SCHEDULE_IDENTITY_PATCH_OK');
